=== chiemeliecoder/sql_musicmarketplaceJson/src/main/resources/musicdata.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="musicdata.xsd">

    <xsd:element name="User">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="userId" type="xsd:int"/>
                <xsd:element name="name" type="xsd:string"/>
                <xsd:element name="email" type="xsd:string"/>
                <xsd:element name="password" type="xsd:string"/>
                <xsd:element name="userProfile">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="id" type="xsd:int"/>
                            <xsd:element name="bio" type="xsd:string"/>
                            <xsd:element name="profileimage" type="xsd:string"/>
                            <xsd:element name="location" type="xsd:string"/>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
                <xsd:element name="playlistList">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="playlist" minOccurs="0" maxOccurs="unbounded">
                                <xsd:complexType>
                                    <xsd:sequence>
                                        <xsd:element name="playlistid" type="xsd:int"/>
                                        <xsd:element name="playlistName" type="xsd:string"/>
                                    </xsd:sequence>
                                </xsd:complexType>
                            </xsd:element>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
                <xsd:element name="wishlistList">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="wishlist" minOccurs="0" maxOccurs="unbounded">
                                <xsd:complexType>
                                    <xsd:sequence>
                                        <xsd:element name="wishlistid" type="xsd:int"/>
                                        <xsd:element name="name" type="xsd:string"/>
                                        <xsd:element name="albumList">
                                            <xsd:complexType>
                                                <xsd:sequence>
                                                    <xsd:element name="album" minOccurs="0" maxOccurs="unbounded">
                                                        <xsd:complexType>
                                                            <xsd:sequence>
                                                                <xsd:element name="albumid" type="xsd:int"/>
                                                                <xsd:element name="albumName" type="xsd:string"/>
                                                                <xsd:element name="albumDate" type="xsd:date"/>
                                                            </xsd:sequence>
                                                        </xsd:complexType>
                                                    </xsd:element>
                                                </xsd:sequence>
                                            </xsd:complexType>
                                        </xsd:element>
                                    </xsd:sequence>
                                </xsd:complexType>
                            </xsd:element>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

</xsd:schema>

=== chiemeliecoder/sql_musicmarketplaceJson/target/classes/musicdata.xml
<?xml version="1.0" encoding="UTF-8" ?>
    <User xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="musicdata.xsd">
        <userId>1</userId>
        <name>john123</name>
        <email>john@example.com</email>
        <password>password</password>
        <userProfile>
            <id>1</id>
            <bio>John bio</bio>
            <profileimage>profile.jpg</profileimage>
            <location>London</location>
        </userProfile>
        <playlistList>
            <playlist>
                <playlistid>1</playlistid>
                <playlistName>My Playlist</playlistName>
            </playlist>
            <playlist>
                <playlistid>2</playlistid>
                <playlistName>Japan vs Korean</playlistName>
            </playlist>
        </playlistList>
        <wishlistList>
            <wishlist>
                <wishlistid>1</wishlistid>
                <name>john123wish</name>
                <albumList>
                    <album>
                        <albumid>1</albumid>
                        <albumName>1989</albumName>
                        <albumDate>2022-01-01</albumDate>
                    </album>
                    <album>
                        <albumid>2</albumid>
                        <albumName>The Book</albumName>
                        <albumDate>2021-03-01</albumDate>
                    </album>
                </albumList>
            </wishlist>
            <wishlist>
                <wishlistid>2</wishlistid>
                <name>johnjpopwish</name>
                <albumList>
                    <album>
                        <albumid>3</albumid>
                        <albumName>META</albumName>
                        <albumDate>2021-05-17</albumDate>
                    </album>
                    <album>
                        <albumid>4</albumid>
                        <albumName>Bokurano</albumName>
                        <albumDate>2021-03-22</albumDate>
                    </album>
                </albumList>
            </wishlist>
        </wishlistList>
    </User>
