=== chiemeliecoder/sql_musicmarketplaceJson/target/classes/musicdata.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="musicdata.xsd">

    <xsd:element name="User">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="UserId" type="xsd:int"/>
                <xsd:element name="name" type="xsd:string"/>
                <xsd:element name="email" type="xsd:string"/>
                <xsd:element name="password" type="xsd:string"/>
                <xsd:element name="userProfile">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="Id" type="xsd:int"/>
                            <xsd:element name="Bio" type="xsd:string"/>
                            <xsd:element name="ProfileImage" type="xsd:string"/>
                            <xsd:element name="Location" type="xsd:string"/>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
                <xsd:element name="playlistList">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="Playlist" minOccurs="0" maxOccurs="unbounded">
                                <xsd:complexType>
                                    <xsd:sequence>
                                        <xsd:element name="PlaylistId" type="xsd:int"/>
                                        <xsd:element name="PlaylistName" type="xsd:string"/>
                                    </xsd:sequence>
                                </xsd:complexType>
                            </xsd:element>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
                <xsd:element name="wishlistList">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="Wishlist" minOccurs="0" maxOccurs="unbounded">
                                <xsd:complexType>
                                    <xsd:sequence>
                                        <xsd:element name="WishlistId" type="xsd:int"/>
                                        <xsd:element name="Name" type="xsd:string"/>
                                        <xsd:element name="albums">
                                            <xsd:complexType>
                                                <xsd:sequence>
                                                    <xsd:element name="Album" minOccurs="0" maxOccurs="unbounded">
                                                        <xsd:complexType>
                                                            <xsd:sequence>
                                                                <xsd:element name="AlbumId" type="xsd:int"/>
                                                                <xsd:element name="AlbumTitle" type="xsd:string"/>
                                                                <xsd:element name="ReleaseDate" type="xsd:date"/>
                                                            </xsd:sequence>
                                                        </xsd:complexType>
                                                    </xsd:element>
                                                </xsd:sequence>
                                            </xsd:complexType>
                                        </xsd:element>
                                    </xsd:sequence>
                                </xsd:complexType>
                            </xsd:element>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

</xsd:schema>

=== chiemeliecoder/sql_musicmarketplaceJson/src/main/resources/musicdata.xml
<User xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="musicdata.xsd">
    <UserId>1</UserId>
    <name>john123</name>
    <email>john@example.com</email>
    <password>password</password>
    <userProfile>
        <Id>1</Id>
        <Bio>John bio</Bio>
        <ProfileImage>profile.jpg</ProfileImage>
        <Location>London</Location>
    </userProfile>
    <playlistList>
        <Playlist>
            <PlaylistId>1</PlaylistId>
            <PlaylistName>My Playlist</PlaylistName>
        </Playlist>
        <Playlist>
            <PlaylistId>2</PlaylistId>
            <PlaylistName>Japan vs Korean</PlaylistName>
        </Playlist>
    </playlistList>
    <wishlistList>
        <Wishlist>
            <WishlistId>1</WishlistId>
            <Name>john123wish</Name>
            <albums>
                <Album>
                    <AlbumId>1</AlbumId>
                    <AlbumTitle>1989</AlbumTitle>
                    <ReleaseDate>2022-01-01</ReleaseDate>
                </Album>
                <Album>
                    <AlbumId>2</AlbumId>
                    <AlbumTitle>The Book</AlbumTitle>
                    <ReleaseDate>2021-03-01</ReleaseDate>
                </Album>
            </albums>
        </Wishlist>
        <Wishlist>
            <WishlistId>2</WishlistId>
            <Name>johnjpopwish</Name>
            <albums>
                <Album>
                    <AlbumId>3</AlbumId>
                    <AlbumTitle>META</AlbumTitle>
                    <ReleaseDate>2021-05-17</ReleaseDate>
                </Album>
                <Album>
                    <AlbumId>4</AlbumId>
                    <AlbumTitle>Bokurano</AlbumTitle>
                    <ReleaseDate>2021-03-22</ReleaseDate>
                </Album>
            </albums>
        </Wishlist>
    </wishlistList>
</User>
